# Generated by Django 5.1.6 on 2025-03-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_learningpath_project_project_topics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='required_skills',
            new_name='subjects',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
    ]
