"""Add assigned_project_id to User model

Revision ID: 1c83ff5440f3
Revises: b20bcac6058f
Create Date: 2025-03-05 14:47:19.107655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c83ff5440f3'
down_revision: Union[str, None] = 'b20bcac6058f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('assigned_project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'projects', ['assigned_project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'assigned_project_id')
    # ### end Alembic commands ###
